package com.example.joselara.pizza5;

import android.app.Activity;
import android.os.Bundle;
import android.widget.TextView;

public class HttpExample extends Activity {

    TextView httpStuff;

    @Override
    protected void onCreate(Bundle savedInstanceState){
        // TODO Autogenerated method stub
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout_http);

        httpStuff=findViewById(R.id.httpTxt);
    }

}
